---

- hosts: lupyanlab
  become: yes

  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  pre_tasks:
    - name: Ensure aptitude is installed
      apt: name=aptitude state=present
    - name: Upgrade everything
      apt: upgrade=yes update_cache=yes

  roles:
    - { role: geerlingguy.mysql }

  tasks:
    - name: Copy database structure script to the server
      copy:
        src: scripts/{{ db_structure_file }}
        dest: /tmp/{{ db_structure_file }}
    - name: Setup database tables
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /tmp/{{ db_structure_file }}
